### ISSUE TITLE
Card payment stays uncaptured

### ISSUE THREAD

**Issue by zorrobiwan** [202-ecommerce/stripe_official#71]
PS 1.6.1.7
Module Stripe: 2.3.2

TEST mode

Trying to make a payement with fake card 4242...
Payment is initiated but stays uncaptured in Stripe (as payment method is card and capture method is manual in your code)

Order is in payment accepted status in BO but payment has to be captured manually in Stripe...

Payment should be captured

nb: module is not configure with catch and authorize

**Comment by mribeiro202** [comment]
Hi @zorrobiwan,

Thank you for your issue. We know this bug, can you try to reset the module and try again a payment ?

Can you tell me if it's ok after this ?

**Comment by zorrobiwan** [comment]
Hi @mribeiro202 

problem is still there after a module reset.
Thx for your followup

**Comment by mribeiro202** [comment]
@zorrobiwan 

Ok thank you thank you for trying.
Can you contact my support team ? 
here is the link : https://addons.prestashop.com/en/contact-us?id_product=24922

**Comment by zorrobiwan** [comment]
will do
thx

**Comment by Jakibrn** [comment]
Hello, I have the same problem. do you have a previous version of the module?

**Comment by sanchezt** [comment]
Hello,

You can download the previous version v2.3.1 here : 
https://github.com/202-ecommerce/stripe_official/releases/download/2.3.1/v2.3.1-prod-stripe_official.zip

Don't forget to purge the Prestashop cache and reactivate payment method in BO.

**Comment by ecenturyuk** [comment]
Had the same issue with a client's site and rollback to version 2.3.1 solved it. 

It was on a 1.7.6.5 prestashop version

Never seen this issue before where the order goes through fine for the customer, but the transaction stays uncaptured in the stripe dashboard and then does not create an order in the backend. Do you know whats it's conflicting with?

**Comment by mribeiro202** [comment]
Hi @ecenturyuk ,

We are currently testing the fix for this issue, if everything is OK after our test, i will release it really soon on addons.
I will post here to advertise all of you ;)

**Comment by darkstudio** [comment]
Hi, Same issue here with v2.3.2. i will try to rollback to v2.3.1.

**Comment by netdrag** [comment]
Same here. The webhook returns a status 400. seems to have to do with the changes to the webhook in v2.3.2

**Comment by OpiumCity** [comment]
Same issue with the v2.3.2 on PS 1.7.2

**Comment by marksull** [comment]
This is a horrible bug that has caused us an enormous amount of pain. As @ecenturyuk said, the customer thinks they have paid because the shop said "Order Successfully Placed" and yet nothing is created in the shop, so as a shop owner you are not aware of the problem unless you go into your stripe dashboard and see the long list of "uncaptured" transactions. 2.3.2 is still the version available on prestashop addons and I only updated a few days ago. As soon as this problem was reported above 2.3.2 should have been immediately removed from addons so that additional shops are not impacted????

**Comment by michaeldebetaz** [comment]
Same issue here, on PS 1.7.7.5. I created a ticket on Prestashop Add-on. I'll try to downgrade the module.

**Comment by inspectaclueso** [comment]
I am experiencing similar issues.  I'm running Prestashop 1.7.7.3  Stripe has been working fine until I upgraded to 2.3.2  
After upgrading, I would not know I had received an order.  No order was created in back office and no emails were generated.  The only way I knew an order had been placed was that in Stripe dashboard there was an uncaptured payment sitting there.  I had to manually click to capture the payment and then manually create an order from the customer cart in back office.  Upgrading the module to 2.3.4 did not fix the issue for me.  I downloaded and re-installed 2.3.1 and it is back to working normally.

**Comment by marzenarog** [comment]
Hey guys, im experiencing same problem,  whats the solution pls???? HELPP

**Comment by marzenarog** [comment]
Stripe payment module v2.3.4 from 202 ecommerce   -    I CAN NOT SEE  THE ORDERS IN MY BACK OFFICE  ( PRESTASHOP 1.7.7.5. )

**Comment by michaeldebetaz** [comment]
I reinstalled the plugin on the 2.3.1 version, as recommended by the support team. It works fine, but the test mode is broken.

If you encounter an issue, I would recommend to delete the plugin, reinstall on version 2.3.1 (link above), clear the cache and profit.

**Comment by mrabsinthe** [comment]
@mribeiro202 The bug was introduced in v2.3.2 and it has been reported by several merchants. This is without a doubt one of the most vital modules and yet, the bug is still not fixed in the next version? Can the team provide the working fix ASAP please?

**Comment by inspectaclueso** [comment]
I am not a developer, but after talking with Stripe support and searching the module code I think at least part of the problem is...

In the file... controllers\front\createIntent.php

Line 43:                 $capture_method = 'manual';

I believe this should be 'automatic' as per Stripe documentation...

https://stripe.com/docs/api/payment_intents/create#create_payment_intent-capture_method

I don't know if this would resolve the issue of orders not being created in back office but surely it will complete the transaction without manually having to go into the Stripe dashboard and click capture.  At least then you should get an email from Stripe advising you have received a payment.

**Comment by mribeiro202** [comment]
Hi,

Version 2.3.2 introduced a new payment validation scheme using webhook.

Unfortunately, version 2.3.2 introduced 2 different bugs, leading in Payment Uncaptured in Stripe Dashboard. 

1 - Multiple payment intents (payment attempt) on the same cart. This issue is fixed by version 2.3.4.

2 - In some cases, changing credentials or switching between Test & Prod does not update webhook. This issue will be fixed in the coming days by version 2.3.5. In the meantime, webhook can be manually regenerated following theses steps :
https://help.202-ecommerce.com/stripe-for-prestashop/procedure-to-replace-the-stripe-key-in-the-database/

@inspectaclueso  : thanks for your feedback, but this behaviour is normal :  capture_method is set to manual only for cards, then capture is triggered by webhook (if catch & authorize is disabled).

**Comment by JimmyBillan** [comment]
Hello, You can check if you need to reset your credential on the stripe dashboard.

On the stripe dashboard > developers > webhooks > [choose your endpoints].
On "Webhook attempts" look for charge.succeded "failed", open it. 

If the "Response" is " _No signatures found matching the expected signature for payload_ " then you should update your STRIPE_WEBHOOK_SIGNATURE l

**Comment by BSCrea** [comment]
Hi,

I'm wondering why in v2.3.2, in controllers/front/createIntent.php, on line 42, this :
`            if (Configuration::get(Stripe_official::CATCHANDAUTHORIZE) && Tools::getValue('payment_option') == 'card') {`
became this : 
`            if (Tools::getValue('payment_option') == 'card') {`

It must check if the option CATCHANDAUTHORIZE is set or not. 
Otherwise, the capture methode is always set as manual when there is a payment by card.

**Comment by mribeiro202** [comment]
Hi all,

The last release is now available on PrestaShop addons just here (v2.3.5) ==> https://addons.prestashop.com/en/payment-card-wallet/24922-stripe-official-sca-ready.html

We fix the issue related to webhook signature update.

When you install this version go and check your module configurations, it may be necessary to backup your keys again. A message will appear in the module configuration screen if this is the case, you will simply have to save the configurations.

Do not hesitate to send me feedback after installing and testing version 2.3.5.

Thank you all for your help and kindness.

**Comment by BSCrea** [comment]
Hi again,

@mribeiro202 I have already updated the module. But still, in controllers/front/createIntent.php, on line 42, there's no verification about the CATCHANDAUTHORIZE option. 
That way, every card payment is set on "manual capture"..

**Comment by vcsahu16** [comment]
There is  bug in the Stripe module .

Order is not created because during ValidateOrder call the  function is not getting the secure_key.

The module is trying to create customer object from cart id.

So In the hook Goto line no. 305 and 

Change this line 

$customer = new Customer($this->conveyor['cart']->id);

To

$customer = new Customer($this->conveyor['cart']->id_customer);

**Comment by vcsahu16** [comment]
> Hey guys, im experiencing same problem, whats the solution pls???? HELPP
Hi ,

There is bug in the Stripe module .

Order is not created because during ValidateOrder call the function is not getting the secure_key.

The module is trying to create customer object from cart id.

So In the hook Goto line no. 305 and

Change this line

$customer = new Customer($this->conveyor['cart']->id);

To

$customer = new Customer($this->conveyor['cart']->id_customer);

**Comment by vcsahu16** [comment]
> I am experiencing similar issues. I'm running Prestashop 1.7.7.3 Stripe has been working fine until I upgraded to 2.3.2
> After upgrading, I would not know I had received an order. No order was created in back office and no emails were generated. The only way I knew an order had been placed was that in Stripe dashboard there was an uncaptured payment sitting there. I had to manually click to capture the payment and then manually create an order from the customer cart in back office. Upgrading the module to 2.3.4 did not fix the issue for me. I downloaded and re-installed 2.3.1 and it is back to working normally.

Hi ,
There is bug in the Stripe module .

Order is not created because during ValidateOrder call the function is not getting the $customer->secure_key.

because the module is trying to create customer object from cart id.

So In the /classes/actions/ValidationOrderActions.php Goto line no. 305 and

Change this line

$customer = new Customer($this->conveyor['cart']->id);

To

$customer = new Customer($this->conveyor['cart']->id_customer);

**Comment by Chrisi1321** [comment]
this is unfortunately not working for me

**Comment by vcsahu16** [comment]
> this is unfortunately not working for me

if customer does not have the key  Then  you can try this .
In the /classes/actions/ValidationOrderActions.php Go near  line no. 310:

Replace

if (isset($customer->secure_key)) {

$this->conveyor['secure_key'] = $customer->secure_key;

} else {

$this->conveyor['secure_key'] = false;

}

with

 

if (isset($this->conveyor['cart']->secure_key)) {

$this->conveyor['secure_key'] = $this->conveyor['cart']->secure_key;

} else {

$this->conveyor['secure_key'] = false;

}

Hope this will work for you. Thanks

**Comment by mribeiro202** [comment]
Hi @vcsahu16 ,

Thank you for your comment, we are currently looking into this issue, we will keep you informed of our progress.

**Comment by Chrisi1321** [comment]
The issue is that the order only gets validated for one of my 3 multishops. There must be an issue with the multishop function

**Comment by eggfriedrice** [comment]
@mribeiro202 any news on this issue?

We're seeing lots of this "PaymentModule::validateOrder - Secure key does not match" issue and uncaptured payments.

My STRIPE_WEBHOOK_SIGNATURE config is correct - it matches the webhook in Stripe.

I'm about to rollback from 2.3.5.

**Comment by mribeiro202** [comment]
hi @eggfriedrice ,

Our support on the module will be able to help you to solve this problem I suggest you to contact him on this link ==> https://addons.prestashop.com/en/contact-us?id_product=24922

**Comment by Ashley-Butcher** [comment]
> The issue is that the order only gets validated for one of my 3 multishops. There must be an issue with the multishop function

I am suspecting this too. As I commented on another issue, per store, we see the error "Webhook configuration cannot be accessed, click on save button to fix issue. A new webhook will be created on Stripe." when configuring the Stripe module.

If we save the config, it works (fixes the webhook), but only for that store. If we click "save" in another store context, then it's fixed only for THAT store now, and the other previous store again shows a setup problem. I suspect that webhooks became mandatory but multistore environments are not correctly supported yet.

**Comment by Comval202** [comment]
Hi all,

The last release is now available on PrestaShop addons just here (v2.3.6) ==> https://addons.prestashop.com/en/payment-card-wallet/24922-stripe-official-sca-ready.html

Do not hesitate to send feedback after installing and testing version 2.3.6.

We are currently try to reproduce the multistore issue, could you please open an incident on https://addons.prestashop.com/en/contact-us?id_product=24922

Thank you all for your help.

**Comment by Ashley-Butcher** [comment]
This problem still occurs in 2.3.6 in multistore - see also issue #93. If you are struggling to reproduce it, it may help to know that we have 10 shops:

Shop 1 and shop 10 are in one group, shops 2 to 9 are in another group. We usually have Stripe transactions in shops 2-9 and none seem to work properly as far as we can tell. Carts are shared between stores in the second shop group, but not the first, and obviously carts cannot be shared across shop groups. I suspect there is an issue with the store context when the webhook calls into PrestaShop, i.e. it defaults to shop with the ID 1, making carts in other shops not visible. We're using PrestaShop version 1.7.7.8.

**Comment by githubjonny** [comment]
We still have this issue on our site. Not a multisite. PS 1.7.7.8 / v2.3.6 - by 202 ecommerce. Webhook keys are correct. 
It's strange as most orders go through without any issues. However, 2 yesterday (out of 20+) are stuck as "uncaptured".

**Comment by darkstudio** [comment]
> We still have this issue on our site. Not a multisite. PS 1.7.7.8 / v2.3.6 - by 202 ecommerce. Webhook keys are correct. It's strange as most orders go through without any issues. However, 2 yesterday (out of 20+) are stuck as "uncaptured".

pfffff.. this is why we haven't not yet updated the module... always on 2.3.2.

**Comment by Ashley-Butcher** [comment]
> We have tried 2.3.7 (provided by the dev) but the issue still exists. What API is everyone using on here in stripe? 2020-08-27 or 2019-08-14? I think we are going to move to prestashop checkout (annoying as I prefer stripe) but the language barrier when communication with the dev means questions are being left unanswered and due to GDPR providing access to the server/PS admin isn't an option.

We're in the EU and use Mollie for debit card transactions, Stripe for credit card transactions. Mollie is our backup for credit card transactions if Stripe isn't working (which is very often lately), but we will probably switch to Mollie permanently as the extra brokerage fee on CC transactions via Mollie is probably worth it as their module works very well, and their support and service is outstanding.

> I also haven't managed to find any link as to why some orders go through fine and others fail. Has anyone else noticed a pattern with their uncaptured orders?

For us it's every order.

> Spoke to stripe and it's Interesting that the payments in previous modules (before the errors started happening), the capture method was passed as automatic (not manual).

This is a module setting now since a recent version ("Enable separate authorization and capture.") - we have this disabled because we want it to be automatic, but indeed it looks like it's never captured automatically.

However, I think it's correct not to capture it until the order has been booked in prestashop, just in case something breaks in prestashop (i.e. bug in PS or in another module). However, for that to work, the Stripe module really needs to be very robustly developed.

**Comment by darkstudio** [comment]
> By the way, indeed, I see that the `capture_method` value is `manual` in the payment_intents calls to Stripe. I have checked the code, and I don't have time at the moment to dig into this unfortunately.
> 
> While maybe this should be `automatic` instead of `manual`, I think it might be a part of their new internal workflow where they will probably capture the payment once they can confirm the order has been accepted/stored in PrestaShop correctly. It seems like a reasonable thing to do (if it worked reliably).
> 
> Since _all_ of our Stripe transactions are going uncaptured, I don't have anything to dig into. For the orders you have that were captured properly, can you maybe check in stripe -> developers -> logs for a payment_intents POST and see if that one also has `capture_method` set to `manual`.

Very strange... i have same issue with a installed prestashop (where i have updated stripe) but with a fresh installed prestashop installed directly with last stripe module, no issue occured.
Its totaly strange because i have totaly uninstalled and clean stripe module from installed prestashop and reinstalled module, issue still the same.
FOr me => go back 2.3.2 . we wait a robust fix :)

**Comment by clotairer** [comment]
We publish last week the release 2.4.0 witch solve issued about uncaptured payments.

You can update your addons. If you have any trouble do not hesitate to contact our technical support here : https://addons.prestashop.com/en/contact-us?id_product=24922

**Comment by inspectaclueso** [comment]
Has anyone tried the new 2.4.0 Stripe module yet on PS 1.7.7?  I'm currently still using 2.3.1 due to the uncaptured payments/no order created issue and previous updates didn't resolve it so hesitant to install and miss orders again.

**Comment by clotairer** [comment]
We have broadcast the module 2.4.0 in bêta during 4 weeks. All return has been successful.

Do not hesitate to « ping » me if you need help by sending a message on this form https://addons.prestashop.com/en/contact-us?id_product=24922

**Comment by darkstudio** [comment]
For me, Stuck and rollback to 2.3.2 since 02 march 2021 because stripe can't assume problems if we have any order /capture problems and my client has exeeced by a problem with stripe, if i update and module cause a problem, me and stripe losse client forever.

**Comment by clotairer** [comment]
@darkstudio ask me if you need help for one of your customers. Send me your demand here https://addons.prestashop.com/en/contact-us?id_product=24922 by mention me, I'll try to found a direct solution for you. Today or when you'll found time.
Thank you.

**Comment by homegourmet** [comment]
hi, issue still there. using PrestaShop 1.7.7.3 and module 2.4.1 for Stripe.... 
Two issues : 
1/ Payment Uncaptured for orders made with VISA cards
2/ Order **not created** in PrestaShop for some payements made by Bancontact.

This is really a serious, and longstanding issue...

**Comment by homegourmet** [comment]
Thanks for the quick reply. 
Has the bug been completely fixed now with this version? Because 2.4.1 version is heavily modified on my PrestaShop, I will have to do all modifications again.....

**Comment by clotairer** [comment]
We don’t have new cases on our help desk about this issue but I cannot be sure for your specific case. You can try and contact me on tech(at)202-ecommerce.com if needed.

**Comment by homegourmet** [comment]
Thank you much. Will keep you posted.

**Comment by mikeKstm** [comment]
I have updated to the latest version and problem still happens randomly

**Comment by clotairer** [comment]
@mikeKstm could please open a new issue because this one is closed and contain different issue fixed. So we need clear explaination of your problem. You can also contact our support team here https://addons.prestashop.com/en/contact-us?id_product=24922 by mention me.
Thank you.

PS: If you installed the pre release 2.4.4, I've fixed a regression this morning and publish a new zip here : https://github.com/202-ecommerce/stripe_official/releases/tag/2.4.4
